model: "" #eg model: "best_5.onnx"
tracker: "bytetrack.yaml"
device: "cuda:0"
enable: True
threshold: 0.5
input_image_topic: "/image_raw"
image_reliability: 2
namespace: "yolo"
imgsz_height: 640
imgsz_width: 640  
